[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pixelspriteai"
version = "1.1.0"
description = "Lightweight Python library for LLM agents to generate pixel art."
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["Pillow"]

[tool.setuptools]
packages = ["pixelspriteai"]
